_BASE_: "Base-RegionSpot.yaml"
MODEL:
  CLIP_TYPE: CLIP_400M_Large_336
  CLIP_INPUT_SIZE: 336
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
DATASETS:
  TRAIN: ("objects365_train",)
  TEST:  ()
TEST:
  EVAL_PERIOD: 0
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000  
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: './output/regionspot_obj365_bl_336'
